### ISSUE TITLE
[1.16.5 FABRIC] the config is not in the config folder

### ISSUE THREAD

**Issue by quentin452** [Domaman202/AE2AO-Remake#10]
AE2AO update : AE2AO-13.0.0

Since there is no config I can't change it

**Comment by Domaman202** [comment]
I'm sorry, I can't understand what this is connected with, try this version: https://www.curseforge.com/minecraft/mc-mods/ae2ao/files/4064777

**Comment by quentin452** [comment]
site doesn't work

**Comment by Domaman202** [comment]
\=

**Comment by quentin452** [comment]
tried the alpha 13.0.1 and no config in config folder
