### ISSUE TITLE
No textures

### ISSUE THREAD

**Issue by Nickstertjefloor** [Domaman202/AE2AO-Remake#3]
I don't have any textures with any object of the ae2ao mod.
![2021-02-24_13 53 29](https://user-images.githubusercontent.com/78900406/109005015-c5804300-76a9-11eb-8af3-cf227c1ce800.png)

I have this with all the objects of the mod when I place it down. In my inventory I see them, but when placed down I get black and purple squares.

**Comment by Domaman202** [comment]
An interesting bug, I have not seen this before

**Comment by Domaman202** [comment]
Can you tell which mods were installed in the assembly?

**Comment by Nickstertjefloor** [comment]
> Can you tell which mods were installed in the assembly?

Yes, they are all fabric mods.
B=Before the mod download
S=Same time the mod download
A=After the mod download

Iron furnace (B)
Additional bars (S)
Abacus (S)
Adabranium (S)
Adapaxel (S)
Adorn (S)
AE2AO (Mod itself)
All stackable (S)
Allure (S)
Applied energistic 2 (Mod itself)
Arsteurgia (S)
Better Ores (S)
Bits and Chisels (S)
Block Compression (S)
Branders Spawnermod (S)
Byg (B)
Curios (B)
Dank Storage (B)
Data-Loader (A)
Elevator (S)
Enchant plus (S)
Experience container (S)
Fabric-Api (S)
Fabric-installer (B)
Fabric-Language-Kotlin (A)
Fabric-magnet (B)
Hwyla (B)
Identity (B)
Iron Chest (B)
Lambdynamiclights (B)
Mechanix (A)
Modmenu (A)
Mostructures (S)
Mythic metals (S)
Optifine (B)
REI (B)
Shulkerboxtooltip (B)
Sodium (B)
Time Travel Mod (S)
Toro Health (S)
Unforgiving Void (S)
Veinmining (B)
World-Edit (B)
Wurst (B)
Xaeros minimap (A)
Xaeros worldmap (A)

Those are all the mods I have (46 in total)

**Comment by Domaman202** [comment]
ok thx

**Comment by Domaman202** [comment]
can you send me your assembly in the archive?

**Comment by Nickstertjefloor** [comment]
> can you send me your assembly in the archive?

Idk how to😅😅

**Comment by Domaman202** [comment]
please send me an archive with mods

**Comment by Domaman202** [comment]
Sorry i Russian human and don't speak on English

**Comment by Domaman202** [comment]
I'm sure this is not related to my mod. he doesn’t investigate the graphical part, I want to help you

**Comment by Nickstertjefloor** [comment]
I need push access to allow me to send the file

**Comment by Domaman202** [comment]
can you upload the assembly to google disk and throw me a link?

**Comment by Mari023** [comment]
@Nickstertjefloor you use sodium, which is not compatible with ae2
also this is not an issue with this mod, this is between ae2 and sodium

**Comment by Nickstertjefloor** [comment]
> An interesting bug, I have not seen this before

It is fixed now.

Sodium DOES NOT work with AE2AO.

**Comment by Domaman202** [comment]
Sodium DOES NOT work with AE2!!!!!!
