### ISSUE TITLE
Что-то сломалось...

### ISSUE THREAD

**Issue by iiiCpu** [Domaman202/AE2AO-Remake#6]
При загрузке карты Стив выходит в окно. Разные версии выходят одинаково.

Вместо тысячи слов... Логи:
[tl-logger5235910486608748492.txt](https://github.com/Domaman202/AE2AO-Remake/files/7490967/tl-logger5235910486608748492.txt)

**Comment by Domaman202** [comment]
сорри що так долго

**Comment by Domaman202** [comment]
я бухал прост

**Comment by Domaman202** [comment]
крч чекай новую версию мода

**Comment by Domaman202** [comment]
не желаете вместе поиграть?
